CREATE TABLE Albuns
(
    Id INT(10) NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    IdArtista INT(10) NOT NULL,
    ImagemCapa VARCHAR(255) NULL,
    DataLancamento DATETIME NULL
);

ALTER TABLE Albuns
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Albuns
PRIMARY KEY(Id);

ALTER TABLE Albuns
ADD CONSTRAINT Fk_Albuns_Artistas
FOREIGN KEY(IdArtista) REFERENCES Artistas(Id);