CREATE TABLE Artistas
(
    Id INT(10) NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Biografia TEXT NULL,
    Imagem VARCHAR(255) NULL,
    DataCadastro DATETIME NOT NULL
);

ALTER TABLE Artistas
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Artistas
PRIMARY KEY(Id);