CREATE TABLE Usuarios
(
    Id INT(10) NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL,
    Senha VARCHAR(225) NOT NULL,
    DataCadastro DATETIME NOT NULL
);

ALTER TABLE Usuarios
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Usuarios
PRIMARY KEY(Id);

ALTER TABLE Usuarios
CHANGE COLUMN Id int(10) NOT NULL AUTO_INCREMENT,
ADD CONSTRAINT Pk_Usuarios
PRIMARY KEY (Id);
