ALTER TABLE Albuns
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Albuns
PRIMARY KEY(Id);

ALTER TABLE Artistas
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Artistas
PRIMARY KEY(Id);

ALTER TABLE ArtistasSeguidos
ADD CONSTRAINT Pk_ArtistasSeguidos
PRIMARY KEY(IdUsuario, IdArtista);

ALTER TABLE Generos
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Generos
PRIMARY KEY(Id);

ALTER TABLE Musicas
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Musicas
PRIMARY KEY(Id);

ALTER TABLE Playlists
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Playlists
PRIMARY KEY(Id);

ALTER TABLE PlaylistsMusicas
ADD CONSTRAINT Pk_PlaylistsMusicas
PRIMARY KEY(IdPlaylist, IdMusica);

ALTER TABLE Usuarios
CHANGE COLUMN Id Id INT(10) AUTO_INCREMENT NOT NULL,
ADD CONSTRAINT Pk_Usuarios
PRIMARY KEY(Id);